### ISSUE TITLE
订阅知乎专栏 Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by yreme** [DIYgod/RSSHub-Radar#122]
尝试订阅知乎专栏
https://zhuanlan.zhihu.com/c_129133522
出现错误，求修复bug
```bash
TypeError: Cannot read property 'map' of undefined
    at module.exports (/data/wwwroot/rsshub.app/lib/routes/zhihu/zhuanlan.js:37:14)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async cache (/data/wwwroot/rsshub.app/lib/middleware/cache.js:203:9)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/parameter.js:8:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/debug.js:14:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/access-control.js:29:13)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/onerror.js:20:9)
```

**Comment by yreme** [comment]
这个问题原因是，官方的 https://rsshub.app 被知乎封杀，导致无法抓取信息。 

解决方案是，用自建的rsshub 就可以了。

建议在 RSSHub-Radar 增加此 exception的捕获，通知告知解决方案
