### ISSUE TITLE
订阅微博博主的时候出现错误

### ISSUE THREAD

**Issue by study875** [DIYgod/RSSHub-Radar#29]
例如https://rsshub.app/weibo/user/1195230310，会跳出
RSSHub 发生了一些意外:
HTTPError: Response code 418 (I'm a Teapot)
    at EventEmitter. (/app/node_modules/got/source/as-promise.js:74:19)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)

在RSS订阅器中也无法使用

**Comment by DIYgod** [comment]
微博反爬，请自建 RSSHub
